# Generated by Django 6.0.2 on 2026-02-17 22:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FuelStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("opis_truckstop_id", models.IntegerField()),
                ("truckstop_name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=2)),
                ("rack_id", models.IntegerField(blank=True, null=True)),
                ("retail_price", models.DecimalField(decimal_places=3, max_digits=6)),
                ("canonical_key", models.CharField(max_length=400, unique=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("geocode_attempts", models.PositiveIntegerField(default=0)),
                ("is_geocode_failed", models.BooleanField(default=False)),
                ("last_geocoded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["state", "city", "truckstop_name"],
                "indexes": [
                    models.Index(fields=["state"], name="route_plann_state_a5d78a_idx"),
                    models.Index(
                        fields=["latitude", "longitude"], name="route_plann_latitud_e48f11_idx"
                    ),
                    models.Index(fields=["canonical_key"], name="route_plann_canonic_b30d00_idx"),
                ],
            },
        ),
    ]
