# Generated by Django 6.0.2 on 2026-02-17 23:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("route_planner", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fuelstation",
            options={"ordering": ("state", "city", "truckstop_name")},
        ),
    ]
